The `micronaut-kotlin-extension-functions` dependency adds a variety of convenience functions to make using
micronaut with kotlin more user-friendly.

dependency:io.micronaut.kotlin:micronaut-kotlin-extension-functions[]

For example, https://kotlinlang.org/docs/reference/inline-functions.html#reified-type-parameters[reified type parameters]
help alleviate the need for using `::class.java` in many places where it would otherwise be required.

Thus, through defining a reified extension function to something like `BlockingHttpClient` like so:

.Example HttpClient Extensions
[source,kotlin]
----
include::kotlin-extension-functions/src/main/kotlin/io/micronaut/kotlin/http/HttpClientExtensions.kt[tags=clientFunctionSingle]

include::kotlin-extension-functions/src/main/kotlin/io/micronaut/kotlin/http/HttpClientExtensions.kt[tags=clientFunctionList]
----

We are able to use the client a little more succinctly, as shown in this test:

.Test Demonstrating Client Extension usage
[source,kotlin]
----
include::kotlin-extension-functions/src/test/kotlin/io/micronaut/kotlin/http/HttpClientExtensionsTest.kt[tags=usingClientFunctions, indent="0"]
----

As another example, you can use a generic `startApplication<AppClass>` with a configuration lambda and generic `mapError<ExceptionClass>`, as you would might use `Micronaut.build().mainClass(App::class.java).start()`.

.An Example `src/main/kotlin/SimpleApplication.kt` using the extension function.
[source,kotlin]
----
object Application

fun main(args: Array<String>) {
    startApplication<Application>(*args) {
        packages("org.example.app")
        mapError<RuntimeException> { 500 }
    }
}
----

NOTE: You will need to import the functions like this: `import io.micronaut.kotlin.FUNCTION_NAME`

Full documentation of the provided extension functions can be found via https://micronaut-projects.github.io/micronaut-kotlin/latest/api/index.html[the dokka docs for this project].

WARNING: Do be aware when defining extension functions in this project or your own, an extension that shadows a member function may have unexpected behavior, and does not throw a compiler error but rather warns.
See https://discuss.kotlinlang.org/t/why-is-shadowed-extension-not-an-error/7209/11[this Kotlin discussion topic] for the latest information.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-kotlin-extension-fns.html[Using Kotlin Extension Functions in the Micronaut Framework] to learn more.
