plugins {
    id "io.micronaut.build.internal.kotlin-base"
    id "io.micronaut.build.internal.module"
    id("org.jetbrains.dokka")
}
ossIndexAudit {
        excludeCoordinates = [ // Ktor 2.x vulnerable versions
                "org.apache.tomcat:tomcat-catalina:9.0.117",
                "org.apache.tomcat:tomcat-coyote:9.0.120",
                "org.apache.tomcat.embed:tomcat-embed-core:9.0.89",
                "org.apache.tomcat:tomcat-juli:11.0.21",
                "org.eclipse.jetty:jetty-server:12.1.8",
                "org.eclipse.jetty:jetty-http:12.1.8",
                "org.eclipse.jetty:jetty-servlets:11.0.26",
                "org.eclipse.jetty.http2:http2-common:11.0.26",
        ]
}

tasks.matching { it.name.startsWith("dokkaGenerate") }.configureEach {
    dependsOn("kaptKotlin")
}
