plugins {
    id "io.micronaut.build.internal.parent"
    alias(libs.plugins.dokka)
}

repositories {
    mavenCentral()
}

dokka {
    dokkaPublications.html {
        outputDirectory.set(rootProject.layout.buildDirectory.dir("docs/api"))
    }
}

docs.dependsOn(tasks.named("dokkaGenerateHtml"))

def prepareGuideHotfix = tasks.register("prepareGuideHotfix") {
    doLast {
        file("${buildDir}/doc-resources").mkdirs()
    }
}

tasks.named('publishGuide') {
    dependsOn(prepareGuideHotfix)
    dependsOn(tasks.javadoc)
}
