[versions]
micronaut = "5.0.0-M25"
micronaut-platform = "5.0.0-M2"
dokka = "2.2.0"
managed-ktor = "2.3.13"
mockito-kotlin = "2.2.0"
typesafe-config = "1.4.5"
micronaut-gradle-plugin = "5.0.0-M1"
# Micronaut BOMs
micronaut-reactor = "4.0.0-M2"
micronaut-serde = "3.0.0-M8"
[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
boms-ktor = { module = "io.ktor:ktor-bom", version.ref = "managed-ktor" }

jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "managed-ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "managed-ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "managed-ktor" }
ktor-server-jetty = { module = "io.ktor:ktor-server-jetty", version.ref = "managed-ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "managed-ktor" }
ktor-server-tomcat = { module = "io.ktor:ktor-server-tomcat", version.ref = "managed-ktor" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito-kotlin" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }

# Micronaut BOMs
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
